# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simple_hazard <- function(pairwise_distanceS, parametersS) {
    .Call('hopskip_simple_hazard', PACKAGE = 'hopskip', pairwise_distanceS, parametersS)
}

bugs <- function(pairwise_distanceS, parametersS) {
    .Call('hopskip_bugs', PACKAGE = 'hopskip', pairwise_distanceS, parametersS)
}

TestExcessGrowthDistribution <- function() {
    .Call('hopskip_TestExcessGrowthDistribution', PACKAGE = 'hopskip')
}

