# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function(pairwise_distanceS, parametersS) {
    .Call('hopskip_rcpp_hello_world', PACKAGE = 'hopskip', pairwise_distanceS, parametersS)
}

