// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// intersections
SEXP intersections(SEXP sunitsx, SEXP sunitsy, SEXP sendpointsx, SEXP sendpointsy, SEXP sstreetsp0, SEXP sstreetsp1);
RcppExport SEXP hopskip_intersections(SEXP sunitsxSEXP, SEXP sunitsySEXP, SEXP sendpointsxSEXP, SEXP sendpointsySEXP, SEXP sstreetsp0SEXP, SEXP sstreetsp1SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type sunitsx(sunitsxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sunitsy(sunitsySEXP);
    Rcpp::traits::input_parameter< SEXP >::type sendpointsx(sendpointsxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sendpointsy(sendpointsySEXP);
    Rcpp::traits::input_parameter< SEXP >::type sstreetsp0(sstreetsp0SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sstreetsp1(sstreetsp1SEXP);
    __result = Rcpp::wrap(intersections(sunitsx, sunitsy, sendpointsx, sendpointsy, sstreetsp0, sstreetsp1));
    return __result;
END_RCPP
}
// simple_hazard
SEXP simple_hazard(SEXP pairwise_distanceS, SEXP street_matrixS, SEXP parametersS, Rcpp::Function callback);
RcppExport SEXP hopskip_simple_hazard(SEXP pairwise_distanceSSEXP, SEXP street_matrixSSEXP, SEXP parametersSSEXP, SEXP callbackSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type pairwise_distanceS(pairwise_distanceSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type street_matrixS(street_matrixSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type parametersS(parametersSSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type callback(callbackSEXP);
    __result = Rcpp::wrap(simple_hazard(pairwise_distanceS, street_matrixS, parametersS, callback));
    return __result;
END_RCPP
}
// bugs
DataFrame bugs(SEXP pairwise_distanceS, SEXP parametersS);
RcppExport SEXP hopskip_bugs(SEXP pairwise_distanceSSEXP, SEXP parametersSSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type pairwise_distanceS(pairwise_distanceSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type parametersS(parametersSSEXP);
    __result = Rcpp::wrap(bugs(pairwise_distanceS, parametersS));
    return __result;
END_RCPP
}
// TestExcessGrowthDistribution
SEXP TestExcessGrowthDistribution();
RcppExport SEXP hopskip_TestExcessGrowthDistribution() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(TestExcessGrowthDistribution());
    return __result;
END_RCPP
}
// TestCallback
SEXP TestCallback(Function callback);
RcppExport SEXP hopskip_TestCallback(SEXP callbackSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Function >::type callback(callbackSEXP);
    __result = Rcpp::wrap(TestCallback(callback));
    return __result;
END_RCPP
}
// hilbertXY2D
SEXP hilbertXY2D(SEXP sx, SEXP sy, SEXP sn);
RcppExport SEXP hopskip_hilbertXY2D(SEXP sxSEXP, SEXP sySEXP, SEXP snSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type sx(sxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sy(sySEXP);
    Rcpp::traits::input_parameter< SEXP >::type sn(snSEXP);
    __result = Rcpp::wrap(hilbertXY2D(sx, sy, sn));
    return __result;
END_RCPP
}
