// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// simple_hazard
SEXP simple_hazard(SEXP pairwise_distanceS, SEXP parametersS, Function callback);
RcppExport SEXP hopskip_simple_hazard(SEXP pairwise_distanceSSEXP, SEXP parametersSSEXP, SEXP callbackSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type pairwise_distanceS(pairwise_distanceSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type parametersS(parametersSSEXP);
    Rcpp::traits::input_parameter< Function >::type callback(callbackSEXP);
    __result = Rcpp::wrap(simple_hazard(pairwise_distanceS, parametersS, callback));
    return __result;
END_RCPP
}
// bugs
DataFrame bugs(SEXP pairwise_distanceS, SEXP parametersS);
RcppExport SEXP hopskip_bugs(SEXP pairwise_distanceSSEXP, SEXP parametersSSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type pairwise_distanceS(pairwise_distanceSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type parametersS(parametersSSEXP);
    __result = Rcpp::wrap(bugs(pairwise_distanceS, parametersS));
    return __result;
END_RCPP
}
// TestExcessGrowthDistribution
SEXP TestExcessGrowthDistribution();
RcppExport SEXP hopskip_TestExcessGrowthDistribution() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(TestExcessGrowthDistribution());
    return __result;
END_RCPP
}
// TestCallback
SEXP TestCallback(Function callback);
RcppExport SEXP hopskip_TestCallback(SEXP callbackSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Function >::type callback(callbackSEXP);
    __result = Rcpp::wrap(TestCallback(callback));
    return __result;
END_RCPP
}
