// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
DataFrame rcpp_hello_world(SEXP pairwise_distanceS, SEXP parametersS);
RcppExport SEXP hopskip_rcpp_hello_world(SEXP pairwise_distanceSSEXP, SEXP parametersSSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type pairwise_distanceS(pairwise_distanceSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type parametersS(parametersSSEXP);
    __result = Rcpp::wrap(rcpp_hello_world(pairwise_distanceS, parametersS));
    return __result;
END_RCPP
}
